/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaswingcustomcomponentdemo;

import java.awt.Dimension;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaswingcustomcomponentdemo.model.Result;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author kanishka
 */
public class ResultGroup extends javax.swing.JPanel {

    /**
     * Creates new form ResultPanel
     */
    public ResultGroup() {
        initComponents();
    }

    public ResultGroup(List<Result> results, String groupName) {
        initComponents();
        jPanelResultList.setLayout(new BoxLayout(jPanelResultList, BoxLayout.Y_AXIS));
        this.jLabelGroupName.setText(groupName);
        for (Result result : results) {
            ResultItem resItem = new ResultItem(result);
            jPanelResultList.add(resItem);
        }
    }

    public JPanel getjPanelResultList() {
        return jPanelResultList;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelGroupName = new javax.swing.JLabel();
        jPanelResultList = new javax.swing.JPanel();
        jButtonCollapseExpand = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Page Name");

        jLabelGroupName.setForeground(new java.awt.Color(38, 38, 38));
        jLabelGroupName.setText("................");

        jPanelResultList.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("Separator.foreground")));

        javax.swing.GroupLayout jPanelResultListLayout = new javax.swing.GroupLayout(jPanelResultList);
        jPanelResultList.setLayout(jPanelResultListLayout);
        jPanelResultListLayout.setHorizontalGroup(
            jPanelResultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelResultListLayout.setVerticalGroup(
            jPanelResultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        jButtonCollapseExpand.setText("-");
        jButtonCollapseExpand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCollapseExpandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCollapseExpand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelGroupName, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanelResultList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelGroupName)
                    .addComponent(jButtonCollapseExpand))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResultList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonCollapseExpandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCollapseExpandActionPerformed
        if (jPanelResultList.isVisible()) {
            jPanelResultList.setVisible(false);
            jButtonCollapseExpand.setText("+");
        } else {
            jPanelResultList.setVisible(true);
            jButtonCollapseExpand.setText("-");
        }
    }//GEN-LAST:event_jButtonCollapseExpandActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCollapseExpand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelGroupName;
    private javax.swing.JPanel jPanelResultList;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
